// console.log(true && !(false || false));
// console.log(!true && !(false || false));
// console.log('cat' + 'dog');
// console.log(2 + 'pizza');
// console.log(2.5 * 'fish');
// console.log(5 >= 11);
// console.log(5 === 5.0);
// console.log(7 !== 7.1);
// console.log(6 + 6 !== 12);
// console.log(2 > 1 || false );
// console.log('true' === true);
// console.log(10 % 2 === 0);
// console.log('new york'[0]);
// console.log('new york'[1]);
// console.log('san francisco'[2 * 3]);
// console.log('science'.indexOf('x') === -1); 
// console.log('bootcamp'.indexOf('o') > -1);
// console.log('bootcamp'.indexOf('camp'));
// console.log('bootcamp'.indexOf('T'));

console.log(2 + 2);